# set waiting time in seconds compared to real life
# time accelerator divides that time by its amount
# making program faster

# timeSimulator
TIME_ACCELERATOR = 1000
OPENING_TIME = 9
CLOSING_TIME = 21

# tables
TABLES_COUNT = 5
WAITING_TIME = 2000 / TIME_ACCELERATOR
EATING_TIME = 300 / TIME_ACCELERATOR # 300 seconds - 5 minutes in game, with accelerator 300/60 = 5 seconds
TABLES_CAPACITY = 4
MINIMUM_TABLE_CAPACITY = 1
MAXIMUM_TABLE_CAPACITY = 6
MINIMUM_CUSTOMER_ARRIVING_TIME = 180 / TIME_ACCELERATOR
MAXIMUM_CUSTOMER_ARRIVING_TIME = 200 / TIME_ACCELERATOR
MAXIMUM_CUSTOMERS_GROUP = 10

# waiters
WAITERS_COUNT = 3
WALKING_TIME = 20 / TIME_ACCELERATOR

# kitchen
PROFIT_MARGIN = 40 # % of profit margin
COOKING_TIME = 100 / TIME_ACCELERATOR 

# cafe
BALANCE = 1000

# reservation
MIN_RESERVATION_FREQUENCY = 5000 / TIME_ACCELERATOR
MAX_RESERVATION_FREQUENCY = 20000 / TIME_ACCELERATOR